### ISSUE TITLE
`ydim-html` startup not working with daeomontools

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ydim-html#16]
1. `/var/www/ydim.ywesee.com/svc/run`
```
#!/bin/sh
exec 2>&1
ulimit -v 10240000
cd /var/www/ydim.ywesee.com/
PATH=/home/zdavatz/.rbenv/versions/3.2.0/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
exec setuidgid zdavatz bundle exec rackup
```
2. Results in
```
[1] pry(#<Rack::Builder>)> Parsing options from the first comment line is deprecated!
@4000000063b55a4623a6174c RCLConf uses the first existing files of etc/ydim-htmld.yml,/var/ydim/ydim-htmld.yml,/etc/ydim/ydim-htmld.yml
@4000000063b55a4623a61f1c loaded config from /etc/ydim/ydim-htmld.yml
@4000000063b55a470b3583b4 Error loding required libraries no implicit conversion of nil into String
@4000000063b55a470b389cac /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:10:in `join'
@4000000063b55a470b38a094 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063b55a470b38a094 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063b55a470b38a47c /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063b55a470b39b9d4 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server.rb:6:in `require_relative'
@4000000063b55a470b39b9d4 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server.rb:6:in `<top (required)>'
@4000000063b55a470b39bdbc /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/invoice.rb:9:in `require'
@4000000063b55a470b39c1a4 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/invoice.rb:9:in `<top (required)>'
@4000000063b55a470b3ab7bc /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/odba.rb:8:in `require'
@4000000063b55a470b3ab7bc /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/odba.rb:8:in `<top (required)>'
@4000000063b55a470c02bec4
@4000000063b55a470c02c2ac From: /var/www/ydim.ywesee.com/config.ru:69 :
@4000000063b55a470c02c2ac
@4000000063b55a470c02c2ac     64:   process ||= :ydim_html
@4000000063b55a470c02c2ac     65:   my_app = YDIM::Html::Util::RackInterface.new(app: YDIM::Html::Util::App.new)
@4000000063b55a470c02c694     66: rescue  Exception => e
@4000000063b55a470c02c694     67:   puts "Error loding required libraries #{e}"
@4000000063b55a470c02ca7c     68:   puts e.backtrace[0..9].join("\n")
@4000000063b55a470c02ca7c  => 69:   binding.pry
@4000000063b55a470c046c74     70:   exit(1)
@4000000063b55a470c046c74     71: end
@4000000063b55a470c046c74     72:
@4000000063b55a470c04705c     73: app = Rack::ShowExceptions.new(Rack::Lint.new(my_app))
@4000000063b55a470c04705c     74: run app
@4000000063b55a470c04705c
[1] pry(#<Rack::Builder>)> Parsing options from the first comment line is deprecated!
@4000000063b55a4729f0426c RCLConf uses the first existing files of etc/ydim-htmld.yml,/var/ydim/ydim-htmld.yml,/etc/ydim/ydim-htmld.yml
@4000000063b55a4729f04654 loaded config from /etc/ydim/ydim-htmld.yml
```
3. This works great `bundle exec rackup` in `/var/www/ydim.ywesee.com`

**Comment by ngiger** [comment]
Added rackup in Gemfile and pushed it to my repo

**Comment by ngiger** [comment]
The rackup gem is new and only present since August 2022

**Comment by zdavatz** [comment]
After installing Rackup, I am still getting this:
```
@4000000063b5601a0b7017cc /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/odba.rb:8:in `require'
@4000000063b5601a0b701bb4 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/odba.rb:8:in `<top (required)>'
@4000000063b5601a0c369c1c
@4000000063b5601a0c369c1c From: /var/www/ydim.ywesee.com/config.ru:69 :
@4000000063b5601a0c36a004
@4000000063b5601a0c36a004     64:   process ||= :ydim_html
@4000000063b5601a0c36a004     65:   my_app = YDIM::Html::Util::RackInterface.new(app: YDIM::Html::Util::App.new)
@4000000063b5601a0c36a3ec     66: rescue  Exception => e
@4000000063b5601a0c36a3ec     67:   puts "Error loding required libraries #{e}"
@4000000063b5601a0c36a3ec     68:   puts e.backtrace[0..9].join("\n")
@4000000063b5601a0c36a7d4  => 69:   binding.pry
@4000000063b5601a0c36d2cc     70:   exit(1)
@4000000063b5601a0c36d6b4     71: end
@4000000063b5601a0c36d6b4     72:
@4000000063b5601a0c36d6b4     73: app = Rack::ShowExceptions.new(Rack::Lint.new(my_app))
@4000000063b5601a0c36d6b4     74: run app
@4000000063b5601a0c36da9c
[1] pry(#<Rack::Builder>)> Parsing options from the first comment line is deprecated!
@4000000063b5601a2af0457c RCLConf uses the first existing files of etc/ydim-htmld.yml,/var/ydim/ydim-htmld.yml,/etc/ydim/ydim-htmld.yml
@4000000063b5601a2af04964 loaded config from /etc/ydim/ydim-htmld.yml
@4000000063b5601b1041a8c4 Error loding required libraries no implicit conversion of nil into String
@4000000063b5601b104229ac /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:10:in `join'
@4000000063b5601b10422d94 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063b5601b1042317c /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063b5601b1042317c /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063b5601b1042411c /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server.rb:6:in `require_relative'
@4000000063b5601b10424504 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/server.rb:6:in `<top (required)>'
@4000000063b5601b10424504 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.2/lib/ydim/invoice.rb:9:in `require'
```

**Comment by zdavatz** [comment]
After this commit: https://github.com/zdavatz/ydim-html/commit/1e6039030c34c7913665b4fd4ae24976e57836c9
now getting:
```
@4000000063b561703a2c0d3c bundler: failed to load command: rackup (/var/www/ydim.ywesee.com/vendor/ruby/3.2.0/bin/rackup)
@4000000063b561703a2daf34 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rack-3.0.0.rc1/lib/rack/builder.rb:92:in `load_file': Parsing options from the first comment line is no longer supported: /var/www/ydim.ywesee.com/config.ru (RuntimeError)
@4000000063b561703a2db704 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rack-3.0.0.rc1/lib/rack/builder.rb:67:in `parse_file'
@4000000063b561703a2db704 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rackup-0.2.3/lib/rackup/server.rb:351:in `build_app_and_options_from_config'
@4000000063b561703a2de5e4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rackup-0.2.3/lib/rackup/server.rb:260:in `app'
@4000000063b561703a2de9cc 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rackup-0.2.3/lib/rackup/server.rb:421:in `wrapped_app'
@4000000063b561703a2de9cc 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rackup-0.2.3/lib/rackup/server.rb:323:in `block in start'
@4000000063b561703a2df584 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rackup-0.2.3/lib/rackup/server.rb:379:in `handle_profiling'
@4000000063b561703a2df96c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rackup-0.2.3/lib/rackup/server.rb:322:in `start'
@4000000063b561703a2df96c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rackup-0.2.3/lib/rackup/server.rb:179:in `start'
@4000000063b561703a2e090c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/rackup-0.2.3/bin/rackup:5:in `<top (required)>'
@4000000063b561703a2e090c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/bin/rackup:25:in `load'
@4000000063b561703a2e0cf4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/bin/rackup:25:in `<top (required)>'
@4000000063b561703a2e0cf4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
@4000000063b561703a2e14c4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
@4000000063b561703a2e18ac 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
@4000000063b561703a2e18ac 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
@4000000063b561703a2e43a4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
@4000000063b561703a2e478c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
@4000000063b561703a2e478c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
@4000000063b561703a2e572c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
@4000000063b561703a2e572c 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
@4000000063b561703a2e5b14 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
@4000000063b561703a2e62e4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
@4000000063b561703a2e62e4 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
@4000000063b561703a2e66cc 	from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
@4000000063b561703a2e6e9c 	from /home/zdavatz/.rbenv/versions/3.2.0/bin//bundle:25:in `load'
@4000000063b561703a2e6e9c 	from /home/zdavatz/.rbenv/versions/3.2.0/bin//bundle:25:in `<main>'
```

**Comment by ngiger** [comment]
Should be fixed. But you must add `--port 8050` as parameter to rackup in the deamontools setup!

**Comment by zdavatz** [comment]
Das wäre dann so: `exec setuidgid zdavatz bundle exec rackup ---port 8050`

**Comment by zdavatz** [comment]
`/var/www/ydim.ywesee.com/svc/run` now looks like this:
```
#!/bin/sh
exec 2>&1
ulimit -v 10240000
cd /var/www/ydim.ywesee.com/
PATH=/home/zdavatz/.rbenv/versions/3.2.0/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
exec setuidgid zdavatz bundle exec rackup --port 8050
```
