### ISSUE TITLE
After fixing #19 error `Error loding required libraries no implicit conversion of nil into String` appears

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ydim-html#20]
```
@4000000063cc0d6a36cf7c8c Error loding required libraries no implicit conversion of nil into String
@4000000063cc0d6a36cfc6c4 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `join'
@4000000063cc0d6a36cfc6c4 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063cc0d6a36cfcaac /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063cc0d6a36cfce94 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063cc0d6a36cfd664 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `require'
@4000000063cc0d6a36cfda4c /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `<top (required)>'
@4000000063cc0d6a36cfda4c /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/invoice.rb:9:in `require'
@4000000063cc0d6a36cfde34 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/invoice.rb:9:in `<top (required)>'
@4000000063cc0d6a36cfe604 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/odba.rb:8:in `require'
@4000000063cc0d6a36cfe604 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/odba.rb:8:in `<top (required)>'
```

**Comment by zdavatz** [comment]
Maybe related to:  https://github.com/zdavatz/ydim/issues/7

**Comment by zdavatz** [comment]
The problem seems to be here: https://github.com/zdavatz/ydim-html/blob/master/lib/ydim/html/config.rb#L10

**Comment by zdavatz** [comment]
```
@4000000063cc0d622bfb4124 bundler: failed to load command: bin/ydimd (bin/ydimd)
@4000000063cc0d622c00dea4 /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `join': no implicit conversion of nil into String (TypeError)
@4000000063cc0d622c00e28c
@4000000063cc0d622c00e28c     ydim_default_dir = File.join(ENV['HOME'], '.ydim')
@4000000063cc0d622c00e674                                  ^^^^^^^^^^^^^^^^^^^^
@4000000063cc0d622c00e674       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:10:in `<class:Server>'
@4000000063cc0d622c00e674       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:9:in `<module:YDIM>'
@4000000063cc0d622c00fde4       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server_config.rb:8:in `<top (required)>'
@4000000063cc0d622c00fde4       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `require'
@4000000063cc0d622c0101cc       from /var/www/ydim.ywesee.com/vendor/ruby/3.2.0/gems/ydim-1.1.1/lib/ydim/server.rb:6:in `<top (required)>'
```

**Comment by zdavatz** [comment]
ydim default dir is `/etc/ydim/`
