### ISSUE TITLE
ydim-html will nicht neustarten

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ydim-html#6]
`/usr/local/bin/bundle-250  exec rackup`

führt zu

```
RCLConf uses the first existing files of etc/ydim-htmld.yml,/root/.ydim/ydim-htmld.yml,/etc/ydim/ydim-htmld.yml
loaded config from /etc/ydim/ydim-htmld.yml
Error loding required libraries Permission denied @ rb_sysopen - /var/www/ydim.ywesee.com/log/2019/12/04/Ydim-Html_log
/var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/chrono_logger-1.1.1/lib/chrono_logger.rb:101:in `initialize'
/var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/chrono_logger-1.1.1/lib/chrono_logger.rb:101:in `open'
/var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/chrono_logger-1.1.1/lib/chrono_logger.rb:101:in `create_logfile'
/var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/chrono_logger-1.1.1/lib/chrono_logger.rb:94:in `rescue in open_logfile'
/var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/chrono_logger-1.1.1/lib/chrono_logger.rb:90:in `open_logfile'
/var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/chrono_logger-1.1.1/lib/chrono_logger.rb:72:in `initialize'
/var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/chrono_logger-1.1.1/lib/chrono_logger.rb:22:in `new'
/var/www/ydim.ywesee.com/vendor/ruby/2.5.0/gems/chrono_logger-1.1.1/lib/chrono_logger.rb:22:in `initialize'
/var/www/ydim.ywesee.com/config.ru:33:in `new'
/var/www/ydim.ywesee.com/config.ru:33:in `block in <main>'
ruby/2.5.0 isn't supported by this pry-doc version

From: /var/www/ydim.ywesee.com/config.ru @ line 70 :

    65:   my_app = YDIM::Html::Util::RackInterface.new(app: YDIM::Html::Util::App.new)
    66: rescue  Exception => e
    67:   puts "Error loding required libraries #{e}"
    68:   puts e.backtrace[0..9].join("\n")
    69:   binding.pry
 => 70:   exit(1)
    71: end
    72: 
    73: app = Rack::ShowExceptions.new(Rack::Lint.new(my_app))
    74: run app
```

**Comment by zdavatz** [comment]
this directory `/var/www/ydim.ywesee.com/log/2019/12/04` as mentioned above, has to be writable by `apache:users`
